### ISSUE TITLE
cant import { SchemaScript }

### ISSUE THREAD

**Issue by leo-paz** [Operation-Nation/sanity-plugin-schema-markup#11]
Hi,

Really appreciate the plugin you've built for sanity. It works well in sanity but when I try to import it like so

`import { SchemaScript } from "@operationnation/sanity-plugin-schema-markup"`

my ts config has `"moduleResolution": "node"` in it but i tried to switch it to use `bundler` but still got the issue.

Importing `import { schemaMarkup } from '@operationnation/sanity-plugin-schema-markup';` in my sanity studio project does work.

**Comment by mwritter** [comment]
Im experiencing the same issue 🙏

```
Module '"@operationnation/sanity-plugin-schema-markup"' has no exported member 'SchemaScript'.
```

![Screen Shot 2024-05-22 at 14 00 56 PM](https://github.com/Operation-Nation/sanity-plugin-schema-markup/assets/14057928/822c7398-5670-46e4-8597-95cf0eb970c9)
