### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by 88Navistar** [Operation-Nation/sanity-plugin-schema-markup#8]
Build is failing after the latest update 1.0.10.

Message
/components/SchemaMarkUp.tsx
**Attempted import error: 'SchemaScript' is not exported from '@operationnation/sanity-plugin-schema-markup' (imported as 'SchemaScript').**

Rolling back to 1.0.0 resolves issue,

**Comment by mechtiis** [comment]
`SchemaScript` has been moved to a separate folder. 
Update the import statement
`import { SchemaScript } from '@operationnation/sanity-plugin-schema-markup/SchemaScript';`

**Comment by 88Navistar** [comment]
Maybe someone could update the Readme as both imports are now incorrect 

`import { SchemaScript } from '@operationnation/sanity-plugin-schema-markup';
import { Schema } from '../types/Types';

type Props = {
  schema: Schema[];
};

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID;
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET;

const SchemaMarkup = ({ schema }: Props) => {
  return (
	  <SchemaScript schema={schema} projectId={projectId as string} dataset={dataset as string} />
  );
};

export default SchemaMarkup;`

**Comment by ericnation** [comment]
Hi all, sorry the delayed response on this. I accidentally didn't have notifications turned on for this repo 😅 Our developer Shuvo who owns this repo will be back from vacation next week and I'll have him review all these issues and address them. Thank you for your patience.
